version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: product-service
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USER=productuser
  #     - DB_PASSWORD=productpass
  #     - DB_NAME=productdb
  #     - DB_SSLMODE=disable

  postgres:
    image: postgres:latest
    container_name: product-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=productuser
      - POSTGRES_PASSWORD=productpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U productuser -d productdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
